author: sengokyu
description: 外部記憶
exclude:
- ".gitignore"
- ".jekyll-cache"
- CNAME
- README.md
lang: ja-JP
minima:
  date_format: "%Y/%m/%d"
plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-mentions
- jekyll-redirect-from
- jekyll-remote-theme
- jekyll-seo-tag
- jekyll-sitemap
- jemoji
remote_theme: jekyll/minima
repository: https://github.com/sengokyu/sengokyu.github.io
timezone: Asia/Tokyo
title: Coeur de lion
url: https://uart.dev/
