remote_theme: "mmistakes/jekyll-theme-basically-basic"
lang: ja-JP
title: Coeur de lion
description: 外部記憶
url: https://uart.dev/
author: sengokyu
repository: https://github.com/sengokyu/sengokyu.github.io
timezone: Asia/Tokyo
future: true
plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-mentions
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jemoji
exclude:
- ".gitignore"
- ".jekyll-cache"
- CNAME
- README.md
